name: Validar compilación con Docker

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Clonar repo
        uses: actions/checkout@v4

      - name: Listar archivos del repo
        run: |
          pwd
          ls -la
          ls -la server || echo "No existe carpeta server"

      - name: Login DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Setup Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Ejecutar Docker Bake con logs detallados
        uses: docker/bake-action@v4
        with:
          source: docker-bake.hcl
          push: false
          progress: plain
